"""Zip → impact rows for /api/zip-impact and /api/zip-impact-ai."""

ZIP_IMPACT: dict[str, dict] = {
    "30318": {
        "zip": "30318",
        "area": "West Atlanta",
        "bill_before_usd": 118,
        "bill_after_usd": 161,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 12.3,
        "datacenter_capacity_mw": 450,
    },
    "30310": {
        "zip": "30310",
        "area": "West End",
        "bill_before_usd": 122,
        "bill_after_usd": 165,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 14.1,
        "datacenter_capacity_mw": 450,
    },
    "30314": {
        "zip": "30314",
        "area": "Vine City",
        "bill_before_usd": 115,
        "bill_after_usd": 158,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 11.8,
        "datacenter_capacity_mw": 450,
    },
    "30315": {
        "zip": "30315",
        "area": "Summerhill",
        "bill_before_usd": 119,
        "bill_after_usd": 162,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 4.2,
        "datacenter_capacity_mw": 280,
    },
    "30316": {
        "zip": "30316",
        "area": "East Atlanta",
        "bill_before_usd": 124,
        "bill_after_usd": 167,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 5.1,
        "datacenter_capacity_mw": 280,
    },
    "30317": {
        "zip": "30317",
        "area": "Edgewood",
        "bill_before_usd": 121,
        "bill_after_usd": 164,
        "nearest_datacenter": "CyrusOne",
        "distance_mi": 9.8,
        "datacenter_capacity_mw": 320,
    },
    "30312": {
        "zip": "30312",
        "area": "Old Fourth Ward",
        "bill_before_usd": 131,
        "bill_after_usd": 174,
        "nearest_datacenter": "Equinix AT1",
        "distance_mi": 2.1,
        "datacenter_capacity_mw": 95,
    },
    "30308": {
        "zip": "30308",
        "area": "Midtown",
        "bill_before_usd": 138,
        "bill_after_usd": 181,
        "nearest_datacenter": "Equinix AT1",
        "distance_mi": 0.8,
        "datacenter_capacity_mw": 95,
    },
    "30309": {
        "zip": "30309",
        "area": "Ansley Park",
        "bill_before_usd": 142,
        "bill_after_usd": 185,
        "nearest_datacenter": "Equinix AT1",
        "distance_mi": 1.2,
        "datacenter_capacity_mw": 95,
    },
    "30306": {
        "zip": "30306",
        "area": "Virginia Highland",
        "bill_before_usd": 136,
        "bill_after_usd": 179,
        "nearest_datacenter": "Equinix AT1",
        "distance_mi": 3.4,
        "datacenter_capacity_mw": 95,
    },
    "30307": {
        "zip": "30307",
        "area": "Inman Park",
        "bill_before_usd": 133,
        "bill_after_usd": 176,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 3.9,
        "datacenter_capacity_mw": 280,
    },
    "30319": {
        "zip": "30319",
        "area": "Brookhaven",
        "bill_before_usd": 145,
        "bill_after_usd": 188,
        "nearest_datacenter": "CyrusOne",
        "distance_mi": 6.7,
        "datacenter_capacity_mw": 320,
    },
    "30324": {
        "zip": "30324",
        "area": "Morningside",
        "bill_before_usd": 139,
        "bill_after_usd": 182,
        "nearest_datacenter": "CyrusOne",
        "distance_mi": 8.2,
        "datacenter_capacity_mw": 320,
    },
    "30327": {
        "zip": "30327",
        "area": "Buckhead",
        "bill_before_usd": 158,
        "bill_after_usd": 201,
        "nearest_datacenter": "Digital Realty",
        "distance_mi": 7.3,
        "datacenter_capacity_mw": 210,
    },
    "30342": {
        "zip": "30342",
        "area": "Sandy Springs",
        "bill_before_usd": 151,
        "bill_after_usd": 194,
        "nearest_datacenter": "Digital Realty",
        "distance_mi": 5.9,
        "datacenter_capacity_mw": 210,
    },
    "30041": {
        "zip": "30041",
        "area": "Cumming",
        "bill_before_usd": 108,
        "bill_after_usd": 149,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 28.4,
        "datacenter_capacity_mw": 320,
    },
    "30024": {
        "zip": "30024",
        "area": "Suwanee",
        "bill_before_usd": 112,
        "bill_after_usd": 153,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 22.1,
        "datacenter_capacity_mw": 320,
    },
    "30518": {
        "zip": "30518",
        "area": "Buford",
        "bill_before_usd": 109,
        "bill_after_usd": 150,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 25.3,
        "datacenter_capacity_mw": 320,
    },
    "30043": {
        "zip": "30043",
        "area": "Lawrenceville",
        "bill_before_usd": 111,
        "bill_after_usd": 152,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 18.7,
        "datacenter_capacity_mw": 320,
    },
    "30044": {
        "zip": "30044",
        "area": "Lawrenceville South",
        "bill_before_usd": 110,
        "bill_after_usd": 151,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 19.2,
        "datacenter_capacity_mw": 320,
    },
    "30060": {
        "zip": "30060",
        "area": "Marietta",
        "bill_before_usd": 114,
        "bill_after_usd": 155,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 15.3,
        "datacenter_capacity_mw": 450,
    },
    "30062": {
        "zip": "30062",
        "area": "East Marietta",
        "bill_before_usd": 116,
        "bill_after_usd": 157,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 16.1,
        "datacenter_capacity_mw": 450,
    },
    "30066": {
        "zip": "30066",
        "area": "Canton Road Marietta",
        "bill_before_usd": 113,
        "bill_after_usd": 154,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 17.2,
        "datacenter_capacity_mw": 450,
    },
    "30067": {
        "zip": "30067",
        "area": "East Cobb",
        "bill_before_usd": 128,
        "bill_after_usd": 169,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 14.8,
        "datacenter_capacity_mw": 450,
    },
    "30068": {
        "zip": "30068",
        "area": "East Cobb North",
        "bill_before_usd": 131,
        "bill_after_usd": 172,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 15.6,
        "datacenter_capacity_mw": 450,
    },
    "30101": {
        "zip": "30101",
        "area": "Acworth",
        "bill_before_usd": 107,
        "bill_after_usd": 148,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 22.4,
        "datacenter_capacity_mw": 450,
    },
    "30102": {
        "zip": "30102",
        "area": "Acworth East",
        "bill_before_usd": 106,
        "bill_after_usd": 147,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 23.1,
        "datacenter_capacity_mw": 450,
    },
    "30114": {
        "zip": "30114",
        "area": "Canton",
        "bill_before_usd": 104,
        "bill_after_usd": 145,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 32.7,
        "datacenter_capacity_mw": 450,
    },
    "30115": {
        "zip": "30115",
        "area": "Canton East",
        "bill_before_usd": 103,
        "bill_after_usd": 144,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 33.4,
        "datacenter_capacity_mw": 450,
    },
    "30188": {
        "zip": "30188",
        "area": "Woodstock",
        "bill_before_usd": 109,
        "bill_after_usd": 150,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 26.8,
        "datacenter_capacity_mw": 450,
    },
    "30189": {
        "zip": "30189",
        "area": "Woodstock West",
        "bill_before_usd": 108,
        "bill_after_usd": 149,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 27.3,
        "datacenter_capacity_mw": 450,
    },
    "30004": {
        "zip": "30004",
        "area": "Alpharetta",
        "bill_before_usd": 142,
        "bill_after_usd": 183,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 24.6,
        "datacenter_capacity_mw": 320,
    },
    "30005": {
        "zip": "30005",
        "area": "Alpharetta East",
        "bill_before_usd": 144,
        "bill_after_usd": 185,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 25.1,
        "datacenter_capacity_mw": 320,
    },
    "30022": {
        "zip": "30022",
        "area": "Johns Creek",
        "bill_before_usd": 146,
        "bill_after_usd": 187,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 21.3,
        "datacenter_capacity_mw": 320,
    },
    "30097": {
        "zip": "30097",
        "area": "Duluth",
        "bill_before_usd": 118,
        "bill_after_usd": 159,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 16.4,
        "datacenter_capacity_mw": 320,
    },
    "30096": {
        "zip": "30096",
        "area": "Duluth West",
        "bill_before_usd": 117,
        "bill_after_usd": 158,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 17.1,
        "datacenter_capacity_mw": 320,
    },
    "30092": {
        "zip": "30092",
        "area": "Peachtree Corners",
        "bill_before_usd": 121,
        "bill_after_usd": 162,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 15.8,
        "datacenter_capacity_mw": 320,
    },
    "30093": {
        "zip": "30093",
        "area": "Norcross",
        "bill_before_usd": 113,
        "bill_after_usd": 154,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 14.9,
        "datacenter_capacity_mw": 320,
    },
    "30071": {
        "zip": "30071",
        "area": "Norcross West",
        "bill_before_usd": 112,
        "bill_after_usd": 153,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 15.3,
        "datacenter_capacity_mw": 320,
    },
    "30047": {
        "zip": "30047",
        "area": "Lilburn",
        "bill_before_usd": 110,
        "bill_after_usd": 151,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 19.7,
        "datacenter_capacity_mw": 320,
    },
    "30045": {
        "zip": "30045",
        "area": "Lawrenceville North",
        "bill_before_usd": 109,
        "bill_after_usd": 150,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 20.4,
        "datacenter_capacity_mw": 320,
    },
    "30346": {
        "zip": "30346",
        "area": "Dunwoody",
        "bill_before_usd": 148,
        "bill_after_usd": 189,
        "nearest_datacenter": "Digital Realty ATL",
        "distance_mi": 8.4,
        "datacenter_capacity_mw": 210,
    },
    "30338": {
        "zip": "30338",
        "area": "Dunwoody North",
        "bill_before_usd": 151,
        "bill_after_usd": 192,
        "nearest_datacenter": "Digital Realty ATL",
        "distance_mi": 9.1,
        "datacenter_capacity_mw": 210,
    },
    "30350": {
        "zip": "30350",
        "area": "Sandy Springs North",
        "bill_before_usd": 153,
        "bill_after_usd": 194,
        "nearest_datacenter": "Digital Realty ATL",
        "distance_mi": 6.8,
        "datacenter_capacity_mw": 210,
    },
    "30328": {
        "zip": "30328",
        "area": "Sandy Springs South",
        "bill_before_usd": 149,
        "bill_after_usd": 190,
        "nearest_datacenter": "Digital Realty ATL",
        "distance_mi": 7.2,
        "datacenter_capacity_mw": 210,
    },
    "30339": {
        "zip": "30339",
        "area": "Vinings",
        "bill_before_usd": 138,
        "bill_after_usd": 179,
        "nearest_datacenter": "Digital Realty ATL",
        "distance_mi": 5.1,
        "datacenter_capacity_mw": 210,
    },
    "30331": {
        "zip": "30331",
        "area": "Ben Hill",
        "bill_before_usd": 116,
        "bill_after_usd": 157,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 13.2,
        "datacenter_capacity_mw": 450,
    },
    "30349": {
        "zip": "30349",
        "area": "College Park",
        "bill_before_usd": 114,
        "bill_after_usd": 155,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 11.4,
        "datacenter_capacity_mw": 450,
    },
    "30337": {
        "zip": "30337",
        "area": "College Park North",
        "bill_before_usd": 113,
        "bill_after_usd": 154,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 10.8,
        "datacenter_capacity_mw": 450,
    },
    "30291": {
        "zip": "30291",
        "area": "Union City",
        "bill_before_usd": 111,
        "bill_after_usd": 152,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 14.7,
        "datacenter_capacity_mw": 450,
    },
    "30213": {
        "zip": "30213",
        "area": "Fairburn",
        "bill_before_usd": 108,
        "bill_after_usd": 149,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 18.3,
        "datacenter_capacity_mw": 450,
    },
    "30214": {
        "zip": "30214",
        "area": "Peachtree City",
        "bill_before_usd": 119,
        "bill_after_usd": 160,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 24.1,
        "datacenter_capacity_mw": 450,
    },
    "30215": {
        "zip": "30215",
        "area": "Peachtree City South",
        "bill_before_usd": 118,
        "bill_after_usd": 159,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 25.3,
        "datacenter_capacity_mw": 450,
    },
    "30268": {
        "zip": "30268",
        "area": "Palmetto",
        "bill_before_usd": 105,
        "bill_after_usd": 146,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 22.7,
        "datacenter_capacity_mw": 450,
    },
    "30236": {
        "zip": "30236",
        "area": "Jonesboro",
        "bill_before_usd": 112,
        "bill_after_usd": 153,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 12.4,
        "datacenter_capacity_mw": 280,
    },
    "30238": {
        "zip": "30238",
        "area": "Jonesboro West",
        "bill_before_usd": 111,
        "bill_after_usd": 152,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 13.1,
        "datacenter_capacity_mw": 280,
    },
    "30260": {
        "zip": "30260",
        "area": "Morrow",
        "bill_before_usd": 113,
        "bill_after_usd": 154,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 10.8,
        "datacenter_capacity_mw": 280,
    },
    "30274": {
        "zip": "30274",
        "area": "Riverdale",
        "bill_before_usd": 112,
        "bill_after_usd": 153,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 11.3,
        "datacenter_capacity_mw": 280,
    },
    "30273": {
        "zip": "30273",
        "area": "Rex",
        "bill_before_usd": 110,
        "bill_after_usd": 151,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 12.7,
        "datacenter_capacity_mw": 280,
    },
    "30297": {
        "zip": "30297",
        "area": "Forest Park",
        "bill_before_usd": 111,
        "bill_after_usd": 152,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 9.4,
        "datacenter_capacity_mw": 280,
    },
    "30354": {
        "zip": "30354",
        "area": "Atlanta South",
        "bill_before_usd": 109,
        "bill_after_usd": 150,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 7.8,
        "datacenter_capacity_mw": 280,
    },
    "30344": {
        "zip": "30344",
        "area": "East Point",
        "bill_before_usd": 115,
        "bill_after_usd": 156,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 6.2,
        "datacenter_capacity_mw": 280,
    },
    "30303": {
        "zip": "30303",
        "area": "Downtown Atlanta",
        "bill_before_usd": 134,
        "bill_after_usd": 177,
        "nearest_datacenter": "Equinix AT1",
        "distance_mi": 1.1,
        "datacenter_capacity_mw": 95,
    },
    "30313": {
        "zip": "30313",
        "area": "Castleberry Hill",
        "bill_before_usd": 129,
        "bill_after_usd": 172,
        "nearest_datacenter": "Equinix AT1",
        "distance_mi": 1.8,
        "datacenter_capacity_mw": 95,
    },
    "31401": {
        "zip": "31401",
        "area": "Savannah",
        "bill_before_usd": 119,
        "bill_after_usd": 158,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 248.0,
        "datacenter_capacity_mw": 280,
    },
    "31404": {
        "zip": "31404",
        "area": "Savannah East",
        "bill_before_usd": 117,
        "bill_after_usd": 156,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 251.0,
        "datacenter_capacity_mw": 280,
    },
    "30901": {
        "zip": "30901",
        "area": "Augusta",
        "bill_before_usd": 113,
        "bill_after_usd": 152,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 145.0,
        "datacenter_capacity_mw": 280,
    },
    "30909": {
        "zip": "30909",
        "area": "Augusta East",
        "bill_before_usd": 112,
        "bill_after_usd": 151,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 147.0,
        "datacenter_capacity_mw": 280,
    },
    "31701": {
        "zip": "31701",
        "area": "Albany",
        "bill_before_usd": 108,
        "bill_after_usd": 147,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 172.0,
        "datacenter_capacity_mw": 280,
    },
    "31601": {
        "zip": "31601",
        "area": "Valdosta",
        "bill_before_usd": 106,
        "bill_after_usd": 145,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 228.0,
        "datacenter_capacity_mw": 280,
    },
    "30501": {
        "zip": "30501",
        "area": "Gainesville",
        "bill_before_usd": 111,
        "bill_after_usd": 150,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 35.4,
        "datacenter_capacity_mw": 320,
    },
    "30506": {
        "zip": "30506",
        "area": "Gainesville East",
        "bill_before_usd": 110,
        "bill_after_usd": 149,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 36.1,
        "datacenter_capacity_mw": 320,
    },
    "30601": {
        "zip": "30601",
        "area": "Athens",
        "bill_before_usd": 114,
        "bill_after_usd": 153,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 68.2,
        "datacenter_capacity_mw": 320,
    },
    "30605": {
        "zip": "30605",
        "area": "Athens East",
        "bill_before_usd": 113,
        "bill_after_usd": 152,
        "nearest_datacenter": "CyrusOne Atlanta",
        "distance_mi": 69.4,
        "datacenter_capacity_mw": 320,
    },
    "31201": {
        "zip": "31201",
        "area": "Macon",
        "bill_before_usd": 110,
        "bill_after_usd": 149,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 82.3,
        "datacenter_capacity_mw": 280,
    },
    "31204": {
        "zip": "31204",
        "area": "Macon North",
        "bill_before_usd": 109,
        "bill_after_usd": 148,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 83.1,
        "datacenter_capacity_mw": 280,
    },
    "30720": {
        "zip": "30720",
        "area": "Dalton",
        "bill_before_usd": 107,
        "bill_after_usd": 146,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 87.4,
        "datacenter_capacity_mw": 450,
    },
    "30721": {
        "zip": "30721",
        "area": "Dalton East",
        "bill_before_usd": 106,
        "bill_after_usd": 145,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 88.2,
        "datacenter_capacity_mw": 450,
    },
    "30161": {
        "zip": "30161",
        "area": "Rome",
        "bill_before_usd": 108,
        "bill_after_usd": 147,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 68.9,
        "datacenter_capacity_mw": 450,
    },
    "30165": {
        "zip": "30165",
        "area": "Rome East",
        "bill_before_usd": 107,
        "bill_after_usd": 146,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 69.7,
        "datacenter_capacity_mw": 450,
    },
    "30701": {
        "zip": "30701",
        "area": "Calhoun",
        "bill_before_usd": 106,
        "bill_after_usd": 145,
        "nearest_datacenter": "QTS Atlanta",
        "distance_mi": 55.3,
        "datacenter_capacity_mw": 450,
    },
    "31093": {
        "zip": "31093",
        "area": "Warner Robins",
        "bill_before_usd": 111,
        "bill_after_usd": 150,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 96.4,
        "datacenter_capacity_mw": 280,
    },
    "31088": {
        "zip": "31088",
        "area": "Warner Robins West",
        "bill_before_usd": 110,
        "bill_after_usd": 149,
        "nearest_datacenter": "Switch Atlanta",
        "distance_mi": 97.2,
        "datacenter_capacity_mw": 280,
    },
}
